# Generated by Django 4.2.9 on 2024-04-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_contactperson_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NS', 'Have not started'), ('IP', 'In progress'), ('CO', 'Project completed')], help_text='Status of the project', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Project update description eg. Started development or Finished project backend', max_length=2000)),
                ('date', models.DateTimeField(help_text='When the project update happened')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.project')),
            ],
        ),
    ]
