# Generated by Django 4.2.9 on 2024-04-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_projectaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccount',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.project'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of contact person', max_length=255, null=True),
        ),
    ]
