# Generated by Django 4.2.9 on 2024-04-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_projectaccount_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='client',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectaccount',
            old_name='client',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectupdate',
            old_name='client',
            new_name='project',
        ),
    ]
