# Generated by Django 4.2.8 on 2024-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('mail', 'Email'), ('instagram', 'Instagram')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social_media_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
