# Generated by Django 4.2.8 on 2024-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_socialmedia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Member full name', max_length=255)),
                ('team', models.CharField(choices=[('business', 'Business Team'), ('design', 'Design Team'), ('software', 'Software Team')], max_length=255)),
                ('role', models.CharField(help_text="'Member' or 'Leader' or 'Member, 'Full Stack Developer'", max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Please compress image, convert type to webp and change size to 500x500 px before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter, https://imageresizer.com/', null=True, upload_to='main_app.File/bytes/filename/mimetype')),
                ('social_medias', models.ManyToManyField(to='main_app.socialmedia')),
            ],
        ),
    ]
