# Generated by Django 4.2.8 on 2024-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_file_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='social_medias',
            field=models.ManyToManyField(blank=True, to='main_app.socialmedia'),
        ),
    ]
