# Generated by Django 4.2.8 on 2024-04-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_member_social_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
