# Generated by Django 4.2.8 on 2024-04-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_member_is_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('mail', 'Email'), ('instagram', 'Instagram'), ('discord', 'Discord')], max_length=255),
        ),
    ]
