# Generated by Django 4.2.8 on 2024-04-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_socialmedia_social_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['social_media']},
        ),
    ]
