# Generated by Django 4.2.9 on 2024-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_socialmedia_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='social_medias',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.member'),
            preserve_default=False,
        ),
    ]
