# Generated by Django 4.2.9 on 2024-04-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_member_social_medias_socialmedia_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='main_app.member'),
        ),
    ]
