# Generated by Django 4.2.11 on 2024-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_section_options'),
        ('main_app', '0011_alter_socialmedia_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Please compress image, convert type to webp and change size to 500x500 px before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter, https://imageresizer.com/', null=True, upload_to='main_app.File/bytes/filename/mimetype')),
                ('tags', models.ManyToManyField(blank=True, to='learning.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
