# Generated by Django 4.2.11 on 2024-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
