# Generated by Django 4.2.11 on 2024-09-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_project_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
