# Generated by Django 4.2.15 on 2024-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_link',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
