# Generated by Django 4.2.15 on 2024-10-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_project_client_project_project_paid_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_project',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
