# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_project_client_project_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_development',
            field=models.BooleanField(default=False, help_text='Toggle if this project is ongoing/in development'),
        ),
    ]
