# Generated by Django 4.2.25 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_delete_non_software_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_leader',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('treasurer', 'Treasurer'), ('officer', 'Officer')], help_text='Leadership role. Leave blank for a regular Software team member.', max_length=50, null=True),
        ),
    ]
