# Generated by Django 4.2.25 on 2026-06-05 07:58

from django.db import migrations


def cleanup_project_image_files(apps, schema_editor):
    Project = apps.get_model('main_app', 'Project')
    File = apps.get_model('main_app', 'File')
    filenames = [
        project.image.name
        for project in Project.objects.all()
        if project.image
    ]
    if filenames:
        File.objects.filter(filename__in=filenames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_member_is_leader_remove_member_team_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_project_image_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
    ]
