# Generated by Django 4.2.25 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_unused_project_and_social_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.CharField(help_text='Short excerpt for feed cards and calendar previews.', max_length=300)),
                ('description', models.TextField(help_text='Full event details shown on the dedicated event page.')),
                ('start_datetime', models.DateTimeField(help_text='When the event starts (HST).')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Optional. Leave blank for open-ended or single-moment events.', null=True)),
                ('location', models.CharField(blank=True, help_text="Venue name, room, or 'Online'.", max_length=255)),
                ('registration_link', models.URLField(blank=True, help_text='Optional RSVP or sign-up URL.', max_length=1000, null=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('meeting', 'Meeting'), ('social', 'Social'), ('info_session', 'Info Session'), ('other', 'Other')], default='other', max_length=20)),
                ('poster', models.ImageField(blank=True, help_text='Optional flyer/poster. Compress to webp before upload.', null=True, upload_to='main_app.File/bytes/filename/mimetype')),
                ('is_published', models.BooleanField(default=False, help_text='Only published events appear on the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime'], name='main_app_ev_start_d_98d2f5_idx'), models.Index(fields=['is_published', 'start_datetime'], name='main_app_ev_is_publ_e83f1d_idx')],
            },
        ),
    ]
