# Generated by Django 4.2.25 on 2026-06-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Repeat weekly on the same weekday as the first meeting. Only for meetings.'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Last calendar day of the recurring series (e.g. semester end).', null=True),
        ),
        migrations.CreateModel(
            name='EventCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField(help_text='Calendar date of the skipped occurrence (e.g. 2026-03-14).')),
                ('reason', models.CharField(blank=True, help_text="Optional note shown on calendar (e.g. 'Spring break').", max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='main_app.event')),
            ],
            options={
                'ordering': ['occurrence_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventcancellation',
            constraint=models.UniqueConstraint(fields=('event', 'occurrence_date'), name='unique_event_cancellation_date'),
        ),
    ]
