# Generated by Django 4.2.25 on 2026-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_event_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_work',
            field=models.BooleanField(default=False, help_text="Toggle on to feature this project in the 'Selected work' section on the home page."),
        ),
    ]
