# Generated by Django 4.2.9 on 2024-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_file_lesson_image_lesson_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Please compress image, convert type to webp and change size to 700x360 px before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter, https://imageresizer.com/', null=True, upload_to='learning.File/bytes/filename/mimetype'),
        ),
    ]
