# Generated by Django 4.2.11 on 2024-04-30 05:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', ckeditor.fields.RichTextField(max_length=3000)),
            ],
        ),
    ]
