# Generated by Django 4.2.11 on 2024-04-30 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_section_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
