# Generated by Django 4.2.11 on 2024-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_section_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
