# Generated by Django 4.2.11 on 2024-05-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_tag_color_alter_lesson_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [models.Case(models.When(color='bg-danger', then=1), models.When(color='bg-success', then=2), models.When(color='bg-primary', then=3), default=4, output_field=models.IntegerField())]},
        ),
    ]
