# Generated by Django 4.2.11 on 2024-05-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'Required (Red)'), ('bg-success', 'Core (Green)'), ('bg-primary', 'Technical Skill (Blue)'), ('bg-secondary', 'Technical Concept (Grey)')], default='bg-primary', max_length=50),
        ),
    ]
