# Generated by Django 4.2.11 on 2024-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='form_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
