# Generated by Django 4.2.11 on 2024-05-01 07:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_rename_form_link_lesson_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=100000),
        ),
    ]
