# Generated by Django 4.2.11 on 2024-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_alter_section_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='skills',
        ),
        migrations.AddField(
            model_name='lesson',
            name='core_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='extension_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='required_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
