# Generated by Django 4.2.11 on 2024-08-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['page']},
        ),
    ]
