# Generated by Django 4.2.18 on 2025-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_section_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
