# Generated by Django 4.2.18 on 2025-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_lesson_order_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
