# Generated by Django 4.2.18 on 2025-01-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_alter_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completion_time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
