# Generated by Django 4.2.17 on 2025-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_lesson_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
