# Generated by Django 4.2.17 on 2025-02-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_rename_video_link_lessonvideo_video_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
