# Generated by Django 4.2.17 on 2025-02-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_lessonvideo_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='core_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='extension_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='required_lesson',
        ),
    ]
