# Generated by Django 4.2.17 on 2025-02-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_remove_lesson_core_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
