# Generated by Django 4.2.17 on 2025-02-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_delete_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
