# Generated by Django 4.2.17 on 2025-02-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='type',
            field=models.CharField(choices=[('concept', 'Concept'), ('follow_along', 'Follow along')], default='follow_along', max_length=15),
        ),
    ]
