# Generated by Django 4.2.25 on 2026-06-05 08:16

from django.db import migrations


def cleanup_lesson_image_files(apps, schema_editor):
    Lesson = apps.get_model('learning', 'Lesson')
    File = apps.get_model('learning', 'File')
    filenames = [
        lesson.image.name
        for lesson in Lesson.objects.all()
        if lesson.image
    ]
    if filenames:
        File.objects.filter(filename__in=filenames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_lessonvideo_type'),
    ]

    operations = [
        migrations.RunPython(cleanup_lesson_image_files, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
