name: Build and Push Docker Image to ECR
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon EC
        id: login-ecr
        run: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 654654366889.dkr.ecr.us-west-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t 8bit-site .

      - name: Tag Docker image
        run: docker tag 8bit-site:latest 654654366889.dkr.ecr.us-west-1.amazonaws.com/8bit-site:latest

      - name: Push Docker image to ECR
        run: docker push 654654366889.dkr.ecr.us-west-1.amazonaws.com/8bit-site:latest