name: Build and Push Server Docker Image to ECR
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 654654366889.dkr.ecr.us-west-2.amazonaws.com

      - name: Build Docker image
        run: docker build --build-arg PROJECT_SECRET="${{ secrets.PROJECT_SECRET }}" -t 8bit-site .

      - name: Tag Docker image
        run: docker tag 8bit-site:latest 654654366889.dkr.ecr.us-west-2.amazonaws.com/8bit-site:latest

      - name: Push Docker image to ECR
        run: docker push 654654366889.dkr.ecr.us-west-2.amazonaws.com/8bit-site:latest

  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into instance one and run commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop $(sudo docker ps -aq)
          sudo docker rm $(sudo docker ps -aq)
          cd apps/8bit-site
          git pull origin main
          sudo docker build -t 8bit-site .
          sudo docker run -d -p 3900:8000 -d 8bit-site
